spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodapp
    username: root
    password: Sopln_pass811
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true